### ISSUE TITLE
Kill Wordpress website

### ISSUE THREAD

**Issue by FrancesCoronel** [fvcproductions/fvcproductions.github.io#51]
Once my Hugo website is fully functional and has an alias for each post in Wordpress, kill Wordpress website

- fix aliases so no page/post from Wordpress site ends up as a 404
- migrate all images to Imgur
- get rid of `\[`
- take screenshots of the old website before killing it

## June 25, 2018

- 691 results: fvcproductions.files.wordpress.com
- 31 results: `\[`

## Archive - Blog

- https://fvcproductions.wordpress.com/blog/archive/

This is the only component left, all other pages have been aliased.

### To-Do

- [] https://fvcproductions.wordpress.com/2015/11/13/hrdevfest-talk/
- [] https://fvcproductions.wordpress.com/2015/10/21/my-designlab-experience/
- [] https://fvcproductions.wordpress.com/2015/08/30/fullstack-academy-reflections/
- [] https://fvcproductions.wordpress.com/2015/08/20/readme-template-for-github/
- [] https://fvcproductions.wordpress.com/2015/08/19/one-week-left-of-fullstack/
- [] https://fvcproductions.wordpress.com/2015/08/05/web-dev-and-web-design-slides-fullstack-academy/
- [] https://fvcproductions.wordpress.com/2015/07/25/fullstack-academy-week-6-review-week/
- [] https://fvcproductions.wordpress.com/2015/07/11/fullstack-academy-week-5/
- [] https://fvcproductions.wordpress.com/2015/07/03/fullstack-academy-week-4/
- [] https://fvcproductions.wordpress.com/2015/06/26/fullstack-academy-week-3/
- [] https://fvcproductions.wordpress.com/2015/06/20/fullstack-academy-week-2/
- [] https://fvcproductions.wordpress.com/2015/06/13/first-week-at-fullstack-academy/
- [] https://fvcproductions.wordpress.com/2015/06/04/fullstack-foundations-goldman-sachs/
- [] https://fvcproductions.wordpress.com/2015/05/20/then-what-shall-we-code-for/
- [] https://fvcproductions.wordpress.com/2015/05/20/bootcamp-me-attempting-to-crowd-source/
- [] https://fvcproductions.wordpress.com/2015/05/17/fullstack-foundations-week-1/
- [] https://fvcproductions.wordpress.com/2015/04/26/damehood-through-hollow-knight/
- [] https://fvcproductions.wordpress.com/2015/04/23/ai-movies/
- [] https://fvcproductions.wordpress.com/2015/04/20/full-of-them/
- [] https://fvcproductions.wordpress.com/2015/04/18/sort-detective-solution/
- [] https://fvcproductions.wordpress.com/2015/04/13/reset-launchpad-with-sorty/
- [] https://fvcproductions.wordpress.com/2015/04/13/what-to-do-week-negative-8/
- [] https://fvcproductions.wordpress.com/2015/04/11/auschwitz-a-doctors-eyewitness-account/
- [] https://fvcproductions.wordpress.com/2015/04/08/lease-template/
- [] https://fvcproductions.wordpress.com/2015/03/29/change-your-icons-yosemite/
- [] https://fvcproductions.wordpress.com/2015/03/28/my-top-3-productivity-apps/
- [] https://fvcproductions.wordpress.com/2015/03/12/jeopardy-template/
- [] https://fvcproductions.wordpress.com/2015/02/24/that-tapia-conference/
- [] https://fvcproductions.wordpress.com/2015/02/20/brief-thoughts-best-bootcamps-switchup/
- [] https://fvcproductions.wordpress.com/2015/02/15/ted-2023/
- [] https://fvcproductions.wordpress.com/2015/02/11/itunes-music-february-2015/
- [] https://fvcproductions.wordpress.com/2015/02/01/adding-awesome-websites-to-your-chrome-app-launcher/
- [] https://fvcproductions.wordpress.com/2015/01/30/adventures-with-aaai-2015/
- [] https://fvcproductions.wordpress.com/2015/01/14/interview-maker-square/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-coding-dojo/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-devleague/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-coding-house/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-with-designation/
- [] https://fvcproductions.wordpress.com/2015/01/05/interview-hack-reactor/
- [] https://fvcproductions.wordpress.com/2015/01/05/prepare-for-coding-bootcamps/
- [] https://fvcproductions.wordpress.com/2014/12/29/aaai-2015-month-left/
- [] https://fvcproductions.wordpress.com/2014/12/29/memorable-experiences-in-gaming/
- [] https://fvcproductions.wordpress.com/2014/12/28/analysis-of-my-scribd-top-5-hits/
- [] https://fvcproductions.wordpress.com/2014/12/28/interview-fullstack-academy/
- [] https://fvcproductions.wordpress.com/2014/12/27/a-short-operation-tips-tricks-4-coding-bootcamps/
- [] https://fvcproductions.wordpress.com/2014/12/27/im-a-noob-when-it-comes-to-programming-where-to-now/
- [] https://fvcproductions.wordpress.com/2014/12/23/first-meetup-first-impressions/
- [] https://fvcproductions.wordpress.com/2014/12/23/analysis-of-the-25-highest-rated-companies-hiring-interns-in-2014-by-glassdoor/
- [] https://fvcproductions.wordpress.com/2014/12/23/week-20/" style="display: 
- [] https://fvcproductions.wordpress.com/2014/12/20/50-lines-for-50-crimes/
- [] https://fvcproductions.wordpress.com/2014/12/17/inkling-1-1/
- [] https://fvcproductions.wordpress.com/2014/12/03/binary-trees-recursion/
- [] https://fvcproductions.wordpress.com/2014/11/10/magnifying-the-bootcamp-research-experience/
- [] https://fvcproductions.wordpress.com/2014/11/10/linked-lists-study-guide/
- [] https://fvcproductions.wordpress.com/2014/10/20/midterm-melodrama-data-structures-with-java/
- [] https://fvcproductions.wordpress.com/2014/10/17/coding-interview-tips-and-tricks/
- [] https://fvcproductions.wordpress.com/2014/10/17/ti-89-tricks-for-calculus/
- [] https://fvcproductions.wordpress.com/2014/10/17/long-lighthearted-lists/
- [] https://fvcproductions.wordpress.com/2014/09/22/limbo-review/
- [] https://fvcproductions.wordpress.com/2014/09/10/giving-back/
- [] https://fvcproductions.wordpress.com/2014/09/04/answer-potc-parchment-riddle/
- [] https://fvcproductions.wordpress.com/2014/09/03/new-html-signature/
- [] https://fvcproductions.wordpress.com/2014/08/09/the-how-tos-when-it-comes-to-java-array/
- [] https://fvcproductions.wordpress.com/2014/08/08/the-day-after-calculus-ended/
- [] https://fvcproductions.wordpress.com/2014/07/20/answer-to-potc-logic-riddle/
- [] https://fvcproductions.wordpress.com/2014/06/21/the-interconnectedness-of-social-networking-sites-and-us/
- [] https://fvcproductions.wordpress.com/2014/05/12/speech-robotics-in-the-workforce/
- [] https://fvcproductions.wordpress.com/2014/05/06/integrating-school-emails-airmail/
- [] https://fvcproductions.wordpress.com/2014/05/02/a-review-of-dont-starve/

http://localhost:3000/about/feedback/ --> should be images from Imgur

fvcproductions.files.wordpress --> remove all instances of this

**Comment by FrancesCoronel** [comment]
#49 is part of this

**Comment by FrancesCoronel** [comment]
## Update

- [x] https://fvcproductions.wordpress.com/2015/11/13/hrdevfest-talk/
- [x] https://fvcproductions.wordpress.com/2015/10/21/my-designlab-experience/
- [x] https://fvcproductions.wordpress.com/2015/08/30/fullstack-academy-reflections/
- [x] https://fvcproductions.wordpress.com/2015/08/20/readme-template-for-github/
- [x] https://fvcproductions.wordpress.com/2015/08/19/one-week-left-of-fullstack/
- [x] https://fvcproductions.wordpress.com/2015/08/05/web-dev-and-web-design-slides-fullstack-academy/
- [x] https://fvcproductions.wordpress.com/2015/07/25/fullstack-academy-week-6-review-week/
- [x] https://fvcproductions.wordpress.com/2015/07/11/fullstack-academy-week-5/
- [x] https://fvcproductions.wordpress.com/2015/07/03/fullstack-academy-week-4/
- [x] https://fvcproductions.wordpress.com/2015/06/26/fullstack-academy-week-3/
- [x] https://fvcproductions.wordpress.com/2015/06/20/fullstack-academy-week-2/
- [x] https://fvcproductions.wordpress.com/2015/06/13/first-week-at-fullstack-academy/
- [x] https://fvcproductions.wordpress.com/2015/06/04/fullstack-foundations-goldman-sachs/
- [x] https://fvcproductions.wordpress.com/2015/05/20/then-what-shall-we-code-for/
- [x] https://fvcproductions.wordpress.com/2015/05/20/bootcamp-me-attempting-to-crowd-source/
- [x] https://fvcproductions.wordpress.com/2015/05/17/fullstack-foundations-week-1/
- [x] https://fvcproductions.wordpress.com/2015/04/26/damehood-through-hollow-knight/
- [x] https://fvcproductions.wordpress.com/2015/04/23/ai-movies/
- [x] https://fvcproductions.wordpress.com/2015/04/20/full-of-them/
- [x] https://fvcproductions.wordpress.com/2015/04/18/sort-detective-solution/
- [x] https://fvcproductions.wordpress.com/2015/04/13/reset-launchpad-with-sorty/
- [x] https://fvcproductions.wordpress.com/2015/04/13/what-to-do-week-negative-8/
- [x] https://fvcproductions.wordpress.com/2015/04/11/auschwitz-a-doctors-eyewitness-account/
- [x] https://fvcproductions.wordpress.com/2015/04/08/lease-template/
- [x] https://fvcproductions.wordpress.com/2015/03/29/change-your-icons-yosemite/
- [x] https://fvcproductions.wordpress.com/2015/03/28/my-top-3-productivity-apps/
- [x] https://fvcproductions.wordpress.com/2015/03/12/jeopardy-template/
- [x] https://fvcproductions.wordpress.com/2015/02/24/that-tapia-conference/
- [x] https://fvcproductions.wordpress.com/2015/02/20/brief-thoughts-best-bootcamps-switchup/
- [x] https://fvcproductions.wordpress.com/2015/02/15/ted-2023/
- [x] https://fvcproductions.wordpress.com/2015/02/11/itunes-music-february-2015/
- [x] https://fvcproductions.wordpress.com/2015/02/01/adding-awesome-websites-to-your-chrome-app-launcher/
- [] https://fvcproductions.wordpress.com/2015/01/30/adventures-with-aaai-2015/
- [] https://fvcproductions.wordpress.com/2015/01/14/interview-maker-square/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-coding-dojo/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-devleague/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-coding-house/
- [] https://fvcproductions.wordpress.com/2015/01/06/interview-with-designation/
- [] https://fvcproductions.wordpress.com/2015/01/05/interview-hack-reactor/
- [] https://fvcproductions.wordpress.com/2015/01/05/prepare-for-coding-bootcamps/
- [] https://fvcproductions.wordpress.com/2014/12/29/aaai-2015-month-left/
- [] https://fvcproductions.wordpress.com/2014/12/29/memorable-experiences-in-gaming/
- [] https://fvcproductions.wordpress.com/2014/12/28/analysis-of-my-scribd-top-5-hits/
- [] https://fvcproductions.wordpress.com/2014/12/28/interview-fullstack-academy/
- [] https://fvcproductions.wordpress.com/2014/12/27/a-short-operation-tips-tricks-4-coding-bootcamps/
- [] https://fvcproductions.wordpress.com/2014/12/27/im-a-noob-when-it-comes-to-programming-where-to-now/
- [] https://fvcproductions.wordpress.com/2014/12/23/first-meetup-first-impressions/
- [] https://fvcproductions.wordpress.com/2014/12/23/analysis-of-the-25-highest-rated-companies-hiring-interns-in-2014-by-glassdoor/
- [] https://fvcproductions.wordpress.com/2014/12/23/week-20/" style="display: 
- [] https://fvcproductions.wordpress.com/2014/12/20/50-lines-for-50-crimes/
- [] https://fvcproductions.wordpress.com/2014/12/17/inkling-1-1/
- [] https://fvcproductions.wordpress.com/2014/12/03/binary-trees-recursion/
- [] https://fvcproductions.wordpress.com/2014/11/10/magnifying-the-bootcamp-research-experience/
- [] https://fvcproductions.wordpress.com/2014/11/10/linked-lists-study-guide/
- [] https://fvcproductions.wordpress.com/2014/10/20/midterm-melodrama-data-structures-with-java/
- [] https://fvcproductions.wordpress.com/2014/10/17/coding-interview-tips-and-tricks/
- [] https://fvcproductions.wordpress.com/2014/10/17/ti-89-tricks-for-calculus/
- [] https://fvcproductions.wordpress.com/2014/10/17/long-lighthearted-lists/
- [] https://fvcproductions.wordpress.com/2014/09/22/limbo-review/
- [] https://fvcproductions.wordpress.com/2014/09/10/giving-back/
- [] https://fvcproductions.wordpress.com/2014/09/04/answer-potc-parchment-riddle/
- [] https://fvcproductions.wordpress.com/2014/09/03/new-html-signature/
- [] https://fvcproductions.wordpress.com/2014/08/09/the-how-tos-when-it-comes-to-java-array/
- [] https://fvcproductions.wordpress.com/2014/08/08/the-day-after-calculus-ended/
- [] https://fvcproductions.wordpress.com/2014/07/20/answer-to-potc-logic-riddle/
- [] https://fvcproductions.wordpress.com/2014/06/21/the-interconnectedness-of-social-networking-sites-and-us/
- [] https://fvcproductions.wordpress.com/2014/05/12/speech-robotics-in-the-workforce/
- [] https://fvcproductions.wordpress.com/2014/05/06/integrating-school-emails-airmail/
- [] https://fvcproductions.wordpress.com/2014/05/02/a-review-of-dont-starve/

**Comment by FrancesCoronel** [comment]
Migrate photos to Google Photos now.

Still need to take screenshots of old website.
